### ISSUE TITLE
specifing account name in config

### ISSUE THREAD

**Issue by abbasudo** [liara-cloud/cli#148]
Hello, thanks for your awesome package.
I work as a freelancer so I have a lot of Liara accounts on my machine. even though I specified the app name in liara.json file, I have to change the account each time I change my workspace. it would be better if I could specify account name in liara.json file. something like my-username/my-app would be great. or even better the cli first searches for a matching app with the name specified in the main account, if not found, it search for it in other accounts too.

**Comment by vashian** [comment]
Hi :wave:  @abbasudo 
Thank you for reaching out and providing your feedback on the **Liara CLI**.

We understand that managing multiple Liara accounts can be challenging, especially when switching between accounts. We appreciate your suggestion to specify the account name in the `liara.json` file. However, due to certain limitations and potential conflicts (e.g., apps with the same name across accounts), this feature might not be feasible.

As an alternative, we recommend using the `--api-token` option for the `liara deploy` command or defining the API token directly in the `liara.json` file. This approach offers a streamlined way to authenticate and manage your accounts, allowing for smoother deployment workflows.

If you have any further questions or suggestions, please feel free to reach out. :tulip:

**Comment by abbasudo** [comment]
Hello @vashian 
I understood that. thanks for your time.
have a great day.

**Comment by vashian** [comment]
Following in-depth discussions within our team, we've decided to implement a new solution to address the challenges associated with managing multiple **Liara** accounts. We will be introducing a new flag, `--account`, for the `liara deploy` command. Additionally, users will have the option to specify their account name in the `liara.json` file for added convenience.

A new pull request will be submitted shortly, addressing these updates. You can track the progress of this implementation and provide feedback until it's ready for merge.

**Comment by abbasudo** [comment]
awsome! thanks a lot.
