### ISSUE TITLE
SyntaxError: Unexpected token 'with'

### ISSUE THREAD

**Issue by AliDlt** [liara-cloud/cli#189]
Hello
After I updated the liara/cli, I got this error from Liara commands, and it worked fine before the update to the last version:
 liara deploy --debug
SyntaxError: Unexpected token 'with'

**Comment by AliDlt** [comment]
And this is my liara.yaml workflow for ci/cd with GitHub actions :
`name: CD-Liara
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@6
          liara deploy --app="projectmanagment" --port=3000 --api-token="$LIARA_TOKEN" --no-app-logs`

**Comment by parishahla** [comment]
> Hello After I updated the liara/cli, I got this error from Liara commands, and it worked fine before the update to the last version: liara deploy --debug SyntaxError: Unexpected token 'with'

Hello dear Ali Dolatabadi,

Thank you for bringing this issue to our attention.

The root cause of the problem was a version incompatibility introduced in the latest update of a third-party package. As a result, our users needed to update their Node.js versions to maintain compatibility with our service. Fortunately, we have addressed this issue.

Please update your Liara CLI to the latest version using the following command:

`npm i -g @liara/cli`

Best regards.

**Comment by parishahla** [comment]
This issue was resolved.
